import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Editor</h1>

        <p className={styles.description}>Small animations with threejs</p>

        <div className={styles.grid}>
          <Link href="/examples/starter">
            <a className={styles.card}>
              <h2>Basic context</h2>
              <p>
                Starter with nextjs and threejs with a scene, camera with
                control, light, cube, render, tick function.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
