import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Small animations with threejs</title>
        <meta name="description" content="Small animations with threejs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Small animations with threejs</h1>

        <div className={styles.grid}>
          <Link href="/examples/hamburger-with-blender">
            <a className={styles.card}>
              <h2>Hamburger</h2>
              <p>Create with blender and exported to threejs</p>
            </a>
          </Link>
          <Link href="/examples/galaxy">
            <a className={styles.card}>
              <h2>Galaxy</h2>
              <p>Generated by particles with threejs</p>
            </a>
          </Link>
          <Link href="/examples/mini-factory">
            <a className={styles.card}>
              <h2>Mini factory</h2>
              <p>A toon mini factory with smoke.</p>
            </a>
          </Link>
          <Link href="/examples/starter">
            <a className={styles.card}>
              <h2>Basic context</h2>
              <p>
                Starter with nextjs and threejs with a scene, camera with
                control, light, cube, render, tick function.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
